services:
  - type: web
    name: crs3-analytics-dashboard
    runtime: docker
    dockerfilePath: ./Dockerfile
    
    # Build configuration
    # buildCommand: ./build.sh  # Commented out - was overwriting config files
    
    # Health check endpoint
    healthCheckPath: /_stcore/health
    
    # Environment variables
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      
      # Add these in Render dashboard as secrets:
      # - OPENAI_API_KEY
      # - DATABASE_URL (if using external database)
      # - REDIS_URL (if using Redis for sessions)
      # - SENTRY_DSN (if using Sentry for error tracking)
      # - AWS_ACCESS_KEY_ID (if using S3)
      # - AWS_SECRET_ACCESS_KEY (if using S3)
      # - S3_BUCKET_NAME (if using S3)
    
    # Auto-deploy configuration
    autoDeploy: false  # Set to true for automatic deploys from GitHub
    
    # Scaling configuration
    plan: free  # Change to 'starter' or higher for production
    
    # Resource limits (adjust based on plan)
    numInstances: 1
    
    # Disk (only available on paid plans)
    # disk:
    #   name: app-storage
    #   mountPath: /mnt/storage
    #   sizeGB: 1
