# Streamlit Configuration for LiteraryAI Studio

[theme]
# Primary color for interactive elements
primaryColor = "#1f77b4"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text
font = "sans serif"

# Base theme
base = "light"

[server]
# Maximum file upload size (in MB)
maxUploadSize = 50

# Maximum message size (in MB)
maxMessageSize = 50

# Enable CORS protection
enableCORS = true

# Enable XSRF protection
enableXsrfProtection = true

# Port - will be overridden by environment variable in production
port = 8501

# Enable development mode
# runOnSave = true

# File watcher type
fileWatcherType = "auto"

# Headless mode (no browser launch)
headless = false

[browser]
# Internet address where users should point their browsers
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

# Port where users should point their browsers
serverPort = 8501

[runner]
# Allows you to type a variable or string by itself in a single line of Python code
magicEnabled = true

[client]
# Controls whether uncaught app exceptions are displayed in the browser
showErrorDetails = "full"

# Change the visibility of items in the toolbar
toolbarMode = "auto"

[logger]
# Level of logging
level = "INFO"

# String format for logging messages
messageFormat = "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
